url: http://blog.sapegin.me
title: Artem Sapegin’s Blog
description: 'Blog of a Berlin based frontend developer who works at Here, makes photos, writes, strokes his dogs and drinks coffee.'
longDescription: |
  <p>I’m a frontend developer living in Berlin, Germany. I work at <a href="https://www.here.com/">Here</a>, and in my spare time I love making photos, writing, hanging out with my dogs and drinking lots of coffee.</p>
  <p><a href="http://sapegin.me/">Check out</a> my projects, <a href="http://twitter.com/iamsapegin">follow me</a> on Twitter or <a href="https://github.com/sapegin/ama">ask me</a> anything.</p>
author: Artem Sapegin
email: artem@sapegin.me
copyrightUrl: http://sapegin.me
twitterName: iamsapegin
postComments: '<a href="{url}">Leave your comments</a> on Medium.'
postFeedback: 'You can improve this post <a href="{url}">by editing it on GitHub</a>.'
aboutTitle: About me
relatedTitle: Read also
search: Search
allPosts: All posts
facebook: Share
twitter: Tweet
poweredBy: 'Powered by <a href="https://github.com/sapegin/fledermaus">Fledermaus</a>, hosted on <a href="https://www.digitalocean.com/?refcode=bb49cbe65bb4">DigitalOcean</a>'
translationHost: http://nano.sapegin.ru
translation: По-русски
searchAction: https://yandex.com/sitesearch
searchId: '2196758'
