url: http://nano.sapegin.ru
title: Наноблог Артёма Сапегина
description: 'Блог фронтенд-разработчика, который живёт в Берлине, работает в Хире, фотографирует, пишет, гладит собак и пьёт кофе.'
longDescription: |
  <p>Я живу в Берлине и работаю фронтенд-разработчиком в <a href="https://www.wayfair.com/">Вэйфейре</a>, а в свободное время фотографирую, глажу своих собак и пью кофе.</p>
  <p>Читайте обо мне <a href="http://sapegin.me/">на моём сайте</a> и подписывайтесь <a href="http://birdwatcher.ru/">на мой блог о фотографии</a> и <a href="http://twitter.com/sapegin">твитер</a>.</p>
author: Артём Сапегин
email: artem@sapegin.ru
copyrightUrl: http://sapegin.ru
twitterName: sapegin
goingEnglish: Вероятнее всего новые посты будут выходить только <a href="http://blog.sapegin.me/">на английском языке</a>.
postFeedback: 'Вы можете улучшить этот пост, <a href="{url}">отредактировав его на Гитхабе</a>.'
aboutTitle: Обо мне
relatedTitle: Читайте дальше
search: Поиск
allPosts: Все посты
facebook: Поделиться
twitter: Твитнуть
poweredBy: 'Работает на <a href="https://github.com/sapegin/fledermaus">Фледермаусе</a>, живёт на <a href="https://www.digitalocean.com/?refcode=bb49cbe65bb4">Диджиталоушене</a>'
translationHost: http://blog.sapegin.me
translation: In English
searchAction: https://yandex.ru/sitesearch
searchId: '2047351'
