url: http://nano.sapegin.ru
title: Наноблог Артёма Сапегина
description: 'Блог фронтенд-разработчика, который живёт в Берлине, работает в Хире, фотографирует, пишет, гладит собак и пьёт кофе.'
longDescription: |
  <p>Я живу в Берлине и работаю фронтенд-разработчиком в <a class="link" href="https://www.here.com/">Хире</a>, а в свободное время фотографирую, пишу, глажу своих собак и пью кофе.</p>
  <p>Читайте обо мне <a class="link" href="http://sapegin.me/">на моём сайте</a> и подпишитесь <a class="link" href="http://birdwatcher.ru/">на мой блог о фотографии</a> и <a class="link" href="http://twitter.com/sapegin">твитер</a>.</p>
author: Артём Сапегин
email: artem@sapegin.ru
copyrightUrl: http://sapegin.ru
tagNames:
  css: CSS
  django: Django
  html: Вёрстка
  javascript: JavaScript
  mac: Mac
  python: Python
  reading: Почитать
  stylus: Stylus
  thoughts: Мысли
  tools: Инструменты
  ui: Интерфейс
  windows: Windows
  wordpress: WordPress
twitterName: sapegin
twitterExtra: data-via="sapegin"
goingEnglish: Вероятнее всего новые посты будут выходить только <a href="http://blog.sapegin.me/" class="link">на английском языке</a>.
postFeedback: 'Вы можете улучшить этот пост, <a href="{url}" class="link">отредактировав его на Гитхабе</a>.'
search: Поиск
allPosts: Все посты
allPostsTagged: '{num, plural, one{# пост} few{# поста} many{# постов} other{# поста}} с тегом <em>{tag}</em>'
allNumPosts: 'Все {num, plural, one{# пост} few{# поста} many{# постов} other{# поста}}'
share: Поделиться
facebook: Фейсбук
twitter: Твитер
gplus: Гугл+
shareOnFacebook: Поделиться постом на Фейсбуке
shareOnTwitter: Поделиться постом в Твитере
shareOnGplus: Поделиться постом в Гугл-плюсе
readMore: Читать дальше…
earlier: Ранее
poweredBy: 'Работает на <a href="https://github.com/sapegin/sweet2" class="link">Свите-2</a>, живёт на <a href="https://www.digitalocean.com/?refcode=bb49cbe65bb4" class="link">Диджиталоушене</a>'
translationHost: http://blog.sapegin.me
translation: In English
searchAction: https://yandex.ru/sitesearch
searchId: '2047351'
